# Generated by Django 4.1.7 on 2023-05-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0002_participants"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Participants",
            new_name="Participant",
        ),
        migrations.AddField(
            model_name="meetup",
            name="participants",
            field=models.ManyToManyField(blank=True, to="meetups.participant"),
        ),
    ]
