# Generated by Django 4.1.7 on 2023-05-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0003_rename_participants_participant_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2021-04-03"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="test@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
